### PR TITLE
Redraw use case diagrams and remove images that aren't used any more

### PR DESCRIPTION
**Pull request by hexrcs**

### CODE REVIEW

**Comment by pm8008** [comment]
1) ex is "extend"!
2) extend- and include relationships are shown by dashed lines with an open arrowhead (maybe make the lines thinner so that the arrowhead is clearly recognizable and doesn't look like a solid triangle)
3) The keywords are surround by double angled quotation marks (guillemets): «extend»
4) I've never seen "extend" and "include" abbreviated in these diagrams. Maybe use the whole words with a smaller font and write them across the lines. see
https://www.omg.org/spec/UML/2.5.1/PDF
p. 646 (pdf page 688)

**Comment by pm8008** [comment]
5) I suggest to have another use case "Configure diagram" that is included by both  "look at data" and "create new diagram"
6) I think that there are both "look at data" and "examine the data" is due to a misunderstanding between Klevia and me. Personally, I'd remove the "examine" case and leave the "look" bubble as it is or rename it to "examine the data" (which sounds a bit more formal/fancy than "look").
7) (this point is a "may" in the UML standard but was required in SWT1:) a rectangle around the use case bubbles that excludes the actor to show the subject of the use cases (aka the system boundary).
In the top left corner of the rectangle it would say:
 «Subsystem» ADIN-Inspector

**Comment by hexrcs** [comment]
OK, so the tool I used to create these graphs can't easily adjust the line widths or arrow styles. Will redraw with another program (perhaps MS Paint) and update the PR accordingly.

@pm8008 
> I suggest to have another use case "Configure diagram" that is included by both "look at data" and "create new diagram"

Could you explain in more detail about this point?

**Comment by pm8008** [comment]
When the user creates a new diagram, it will be unconfigured/empty at first and the user has to configure it (by selecting a diagram type, selecting which data stream to show in this diagram, which keys of the data stream (sender, receiver, packet type, size, ...) to display etc.).

The user may also want to do this while looking at an already existing diagram (e.g. to add another data stream to the diagram). Therefore I think that "Configure diagram" should be a "sub-usecase", i.e. a use case of its own that gets included by "create ..." and "look ...".

I.e. I'd suggest to  add a new use case ellipse with the text "Configure diagram" and place it below and to the right of "create ...". Then add two <<include>> arrows,  one from "look ..." to "configure" and one from "create ..." to "configure".
Sorry for all the trouble :)

**Comment by hexrcs** [comment]
Do the lines/arrows look right to you for the login case? @pm8008 

case_login

**Comment by hexrcs** [comment]
And the other one. Feedbacks? :)

case_examine_data

**Comment by pm8008** [comment]
the login case is perfect; in the second diagram the arrows pointing to "Configure Diagram" should be dashed and have the «include» - annotation
Thanks!

**Comment by hexrcs** [comment]
@pm8008 Updated. Please merge if nothing else needs to be changed.

**Comment by pm8008** [comment]
Great, thanks!

**Pull request merged**
